version: '3'
services:
    mci:
        image: brighthive/master-client-index:1.0.5
        ports:
            - "8001:8000"
        environment:
            - APP_ENV=SANDBOX
            - POSTGRES_USER=brighthive
            - POSTGRES_PASSWORD=test_password
            - POSTGRES_DATABASE=mci_dev
            - POSTGRES_HOSTNAME=postgres_mci
            - POSTGRES_PORT=5432
            - MATCHING_SERVICE_URI=http://mci-matching-service:8000/compute-match
        depends_on:
            - postgres_mci
    postgres_mci:
        image: postgres:11.1
        environment:
            - POSTGRES_USER=brighthive
            - POSTGRES_PASSWORD=test_password
            - POSTGRES_DB=mci_dev
        ports:
            - "5432:5432"
        # Spinning up postgres (when decoupled from the app)
        # assigns the db files to postgres.
        #
        # postgres_mci_1  | The files belonging to this database system will be owned by user "postgres".
        # postgres_mci_1  | This user must also own the server process.
        #
        # Without a designated user, the container does not have an (unprivileged, i.e., not "root")
        # who owns the server process. That's a problem! Because the mci container
        # cannot connect to the database and run migrations.
        user: postgres
    mci-matching-service:
        image: 396527728813.dkr.ecr.us-east-2.amazonaws.com/brighthive/mci-matching-service:latest
        ports:
            - "8888:8000"
        environment:
            - APP_ENV=PRODUCTION
            - POSTGRES_USER=brighthive
            - POSTGRES_PASSWORD=test_password
            - POSTGRES_DATABASE=mci_dev
            - POSTGRES_HOSTNAME=postgres_mci
            - POSTGRES_PORT=5432
networks:
    mci_network:
        external: true
