"""Create MCI database schema.

Revision ID: 5104693f69bb
Revises:
Create Date: 2019-03-18 21:54:37.194707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5104693f69bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('address', sa.String(
                        length=100), nullable=False),
                    sa.Column('city', sa.String(length=100), nullable=False),
                    sa.Column('state', sa.String(length=20), nullable=False),
                    sa.Column('postal_code', sa.String(
                        length=20), nullable=False),
                    sa.Column('country', sa.String(length=2), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('current_status',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('current_status', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('education_level',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('education_level', sa.String(
                        length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('employment_status',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('employment_status', sa.String(
                        length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('ethnicity_race',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('ethnicity_race', sa.String(
                        length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('gender',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('gender', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('source',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('source', sa.String(length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('individual',
                    sa.Column('mci_id', sa.String(length=40), nullable=False),
                    sa.Column('pairin_id', sa.String(
                        length=40), nullable=True),
                    sa.Column('ssn', sa.Integer(), nullable=True),
                    sa.Column('registration_date', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('first_name', sa.String(
                        length=100), nullable=False),
                    sa.Column('middle_name', sa.String(
                        length=100), nullable=True),
                    sa.Column('last_name', sa.String(
                        length=100), nullable=True),
                    sa.Column('date_of_birth', sa.Date(), nullable=False),
                    sa.Column('email_address', sa.String(
                        length=100), nullable=True),
                    sa.Column('telephone', sa.String(
                        length=20), nullable=True),
                    sa.Column('mailing_address_id',
                              sa.Integer(), nullable=True),
                    sa.Column('gender_id', sa.Integer(), nullable=True),
                    sa.Column('ethnicity_and_race_id',
                              sa.Integer(), nullable=True),
                    sa.Column('education_level_id',
                              sa.Integer(), nullable=True),
                    sa.Column('employment_status_id',
                              sa.Integer(), nullable=True),
                    sa.Column('source_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['education_level_id'], [
                        'education_level.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['employment_status_id'], [
                        'employment_status.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['ethnicity_and_race_id'], [
                        'ethnicity_race.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['gender_id'], ['gender.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['mailing_address_id'], [
                        'address.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['source_id'], ['source.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('mci_id')
                    )
    op.create_table('individual_current_status',
                    sa.Column('mci_id', sa.String(length=40), nullable=False),
                    sa.Column('current_status_id',
                              sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['current_status_id'], [
                        'current_status.id'], ),
                    sa.ForeignKeyConstraint(
                        ['mci_id'], ['individual.mci_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('mci_id', 'current_status_id')
                    )
    op.create_table('referral',
                    sa.Column('program_id', sa.Integer(), nullable=False),
                    sa.Column('mci_id', sa.String(length=40), nullable=False),
                    sa.Column('referring_id', sa.Integer(), nullable=False),
                    sa.Column('date_referred', sa.Date(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['mci_id'], ['individual.mci_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('program_id', 'mci_id',
                                            'referring_id', 'date_referred')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referral')
    op.drop_table('individual_current_status')
    op.drop_table('individual')
    op.drop_table('source')
    op.drop_table('gender')
    op.drop_table('ethnicity_race')
    op.drop_table('employment_status')
    op.drop_table('education_level')
    op.drop_table('current_status')
    op.drop_table('address')
    # ### end Alembic commands ###
