"""Add migration for multiple ethnicity/races.

Revision ID: 7da08ea50a5a
Revises: 9b523b424b1d
Create Date: 2019-03-27 16:50:39.479661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da08ea50a5a'
down_revision = '9b523b424b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individual_ethnicity_race',
                    sa.Column('individual_id', sa.String(
                        length=40), nullable=False),
                    sa.Column('ethnicity_race_id',
                              sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['ethnicity_race_id'], [
                        'ethnicity_race.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['individual_id'], ['individual.mci_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint(
                        'individual_id', 'ethnicity_race_id')
                    )
    op.drop_constraint('individual_ethnicity_and_race_id_fkey',
                       'individual', type_='foreignkey')
    op.drop_column('individual', 'ethnicity_and_race_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individual', sa.Column('ethnicity_and_race_id',
                                          sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('individual_ethnicity_and_race_id_fkey', 'individual', 'ethnicity_race', [
                          'ethnicity_and_race_id'], ['id'], ondelete='CASCADE')
    op.drop_table('individual_ethnicity_race')
    # ### end Alembic commands ###
