"""Add user dispositons table.

Revision ID: 9b523b424b1d
Revises: c6c3719e2f79
Create Date: 2019-03-27 12:49:28.912641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b523b424b1d'
down_revision = 'c6c3719e2f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disposition',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('disposition', sa.String(
                        length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('individual_disposition',
                    sa.Column('individual_id', sa.String(
                        length=40), nullable=False),
                    sa.Column('disposition_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['disposition_id'], [
                        'disposition.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['individual_id'], ['individual.mci_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('individual_id', 'disposition_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('individual_disposition')
    op.drop_table('disposition')
    # ### end Alembic commands ###
