"""Replace PAIRIN ID with Vendor ID

Revision ID: e1bdd0f39e93
Revises: 5104693f69bb
Create Date: 2019-03-27 11:53:19.260733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1bdd0f39e93'
down_revision = '5104693f69bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individual', sa.Column('vendor_id', sa.String(length=40), nullable=True))
    op.drop_column('individual', 'pairin_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individual', sa.Column('pairin_id', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_column('individual', 'vendor_id')
    # ### end Alembic commands ###
